name: Publish VSCode extension

on:
  push:
    branches: [release]

jobs:
  release-vs-marketplace:
    runs-on: ubuntu-latest
    environment: deploy-vsce-prod
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install modules
      run: npm install
    # VSCE_PAT must be an organization-scoped PAT: https://dev.azure.com/PollywogGames/_usersSettings/tokens
    - name: VSCE package and publish
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
      run: |
        npx @vscode/vsce package
        npx @vscode/vsce publish --skip-duplicate

  release-open-vsx:
    # following pattern: https://github.com/open-vsx/publish-extensions/blob/master/docs/exampleCI.yaml
    runs-on: ubuntu-latest
    environment: deploy-vsce-prod
    steps:
    - uses: actions/checkout@v4
    # Make sure we're using node 20+
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install modules
      run: npm install
    - name: OVSX package and publish
      env:
        OVSX_PAT: ${{ secrets.OVSX_PAT }}
      run: npx ovsx publish
